// Name resolver — backed by static JSON files we ship under public/db/.
// Item and skill names come straight from the game client GRF (item.json /
// skill.json, generated by tools/build-db.mjs); monster names still come from
// Divine Pride (dp-monster.json, generated by tools/scrape-dp.mjs) since they
// aren't in the client data. On first lookup we fetch each kind's file, parse
// it into an in-memory Map, then serve every subsequent lookup from memory.
// The browser's HTTP cache makes repeat visits free.
//
// No runtime DP queries: the offline scraper is responsible for filling
// in any unlisted view ids (via its Firestore harvest pass), so the
// browser never talks to divine-pride.net.

import type { Replay } from "./rrf/types.js";

type ItemEntry = { name: string; view?: number };
type MonsterEntry = { name: string; hp: number; level: number };
type SkillEntry = { name: string };
// Random-option id -> display template ("ATQM +%d"). Stored as a bare string.
type RandomOptEntry = string;

// vite is configured with `base: "./"`, so relative URLs resolve against
// the current page (works on dev http://localhost:5173/ and on Firebase
// Hosting https://ragnarecap.web.app/ alike). Files live in public/db/
// and ship as-is to the deploy root.
const DB_BASE = "./db";

let items: Map<number, ItemEntry> | null = null;
let monsters: Map<number, MonsterEntry> | null = null;
let skills: Map<number, SkillEntry> | null = null;
let randomOpts: Map<number, RandomOptEntry> | null = null;

let itemsP: Promise<void> | null = null;
let monstersP: Promise<void> | null = null;
let skillsP: Promise<void> | null = null;
let randomOptsP: Promise<void> | null = null;

async function loadKind<T>(
  fileName: string,
): Promise<Map<number, T>> {
  try {
    const res = await fetch(`${DB_BASE}/${fileName}`);
    if (!res.ok) return new Map();
    const data = (await res.json()) as Record<string, T>;
    const map = new Map<number, T>();
    for (const [id, entry] of Object.entries(data)) {
      map.set(Number(id), entry);
    }
    return map;
  } catch {
    return new Map();
  }
}

function loadItems(): Promise<void> {
  if (items) return Promise.resolve();
  if (!itemsP) itemsP = loadKind<ItemEntry>("item.json").then((m) => { items = m; });
  return itemsP;
}
function loadMonsters(): Promise<void> {
  if (monsters) return Promise.resolve();
  if (!monstersP) monstersP = loadKind<MonsterEntry>("dp-monster.json").then((m) => { monsters = m; });
  return monstersP;
}
function loadSkills(): Promise<void> {
  if (skills) return Promise.resolve();
  if (!skillsP) skillsP = loadKind<SkillEntry>("skill.json").then((m) => { skills = m; });
  return skillsP;
}
function loadRandomOpts(): Promise<void> {
  if (randomOpts) return Promise.resolve();
  if (!randomOptsP)
    randomOptsP = loadKind<RandomOptEntry>("randomopt.json").then((m) => { randomOpts = m; });
  return randomOptsP;
}

/**
 * Loads every kind's static JSON in parallel. Resolves once all of them are
 * in memory (or have failed and been recorded as empty maps). Cheap on
 * repeat — already-loaded kinds short-circuit immediately.
 */
export async function prefetchReplay(_replay: Replay): Promise<void> {
  await Promise.all([loadItems(), loadMonsters(), loadSkills(), loadRandomOpts()]);
}

export function getItemName(id: number): string | null {
  return items?.get(id)?.name ?? null;
}

/**
 * Sprite "view" id for an item (the client's `ClassNum`): accessory id for
 * headgears/costumes, robe id for garments, shield/weapon look. Used to render
 * equipped gear on the character viewer. `null` until item.json is regenerated
 * with the `view` field (tools/build-db.mjs), or for items without a view.
 */
export function getItemView(id: number): number | null {
  return items?.get(id)?.view ?? null;
}

export function getMonsterName(id: number): string | null {
  return monsters?.get(id)?.name ?? null;
}

export function getMonsterHp(id: number): number {
  return monsters?.get(id)?.hp ?? 0;
}

export function getSkillName(id: number): string | null {
  return skills?.get(id)?.name ?? null;
}

/**
 * Format a random option ("Bônus Aleatório") for display: fills the client's
 * template with the stored value (`%d` → value, `%%` → literal `%`), e.g.
 * id 19 + value 7 → "ATQM +7". Returns `null` until randomopt.json loads or for
 * unknown ids, so the caller can fall back to a raw `id:value` label.
 */
export function getRandomOptionText(id: number, value: number): string | null {
  const tmpl = randomOpts?.get(id);
  if (!tmpl) return null;
  return tmpl.replace(/%d/g, String(value)).replace(/%%/g, "%");
}
